### ISSUE TITLE
Problème test programme OCaml et Coq

### ISSUE THREAD

**Issue by ghost** [erikmd/tapfa-init.el#5]
Il ne veut pas tester mon programme via Emacs alors que sans Emacs ça marche.

**Comment by erikmd** [comment]
Bonjour @spossoume, désolé pour la réponse tardive,
Peux-tu me dire le message d'erreur que tu vois ? soit dans le mini-buffer, soit en faisant le raccourci clavier <kbd>C-h e</kbd> (= Ctrl+H E)

**Comment by erikmd** [comment]
En devinant un peu, il est possible que le message soit
`Searching for program: No such file or directory, coqtop` (n'est-ce-pas ?)

Dans ce cas, c'est juste que coqtop (ou ocaml) n'est pas dans le PATH au moment où emacs est lancé.
→ Pour corriger le souci au moment où il se présente, il suffit normalement de cliquer sur le menu "OPSW" et de sélectionner un switch opam qui contient coqtop et ocaml, et de réessayer la commande.
→ Pour corriger le souci de façon définitive, si tu es sous Linux ou sous macOS, il suffit de vérifier qu'il y a bien la ligne de commande `eval $(opam env)` à la fin du fichier `~/.bashrc` et de redémarrer l'OS.

Tiens-moi au courant et si ces indications ne suffisent pas, j'aurais besoin de connaître quel OS tu utilises.

**Comment by erikmd** [comment]
Rebonjour @spossoume, est-ce que ton problème a été résolu ?

**Comment by ghost** [comment]
Dsl du retard, grâce à tes explications, j'ai pu résoudre mon problème. Merci
